# Generated by Django 3.0.7 on 2021-01-05 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_breed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LambInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_id', models.IntegerField(verbose_name='配种信息id')),
                ('basic_id', models.IntegerField(blank=True, null=True, verbose_name='入棚后羊基本id')),
                ('tobasic', models.BooleanField(default=False, verbose_name='是否入库')),
                ('logo', models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='羔羊标识')),
                ('ele_num', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='电子耳号')),
                ('pre_num', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='防疫耳号')),
                ('purpose', models.IntegerField(blank=True, choices=[(0, '育苗'), (1, '育肥')], null=True, verbose_name='用途')),
                ('variety', models.IntegerField(blank=True, choices=[(0, '湖羊'), (1, '小尾寒羊'), (2, '无角道赛特'), (3, '黑羊'), (4, '小尾4'), (5, '小尾5'), (6, '小尾6')], null=True, verbose_name='品种')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '母'), (1, '公')], null=True, verbose_name='性别')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
                ('manu_info_id', models.IntegerField(blank=True, null=True, verbose_name='源产地id')),
                ('manu_info_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='产地名')),
                ('state', models.IntegerField(blank=True, choices=[(0, '死亡'), (1, '正常'), (2, '销售')], default=1, null=True, verbose_name='状态')),
                ('birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='出生日期')),
                ('bir_weight', models.FloatField(blank=True, null=True, verbose_name='出生重(kg)')),
                ('wea_weight', models.FloatField(blank=True, null=True, verbose_name='断奶重(kg)')),
                ('house_id', models.IntegerField(blank=True, null=True, verbose_name='圈舍号')),
                ('hurdle_id', models.IntegerField(blank=True, null=True, verbose_name='圈栏号')),
                ('house_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='圈栏名称')),
                ('hurdle_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='圈舍名称')),
                ('mon_age', models.FloatField(blank=True, null=True, verbose_name='月龄')),
                ('father_id', models.IntegerField(blank=True, null=True, verbose_name='父ID')),
                ('mother_id', models.IntegerField(blank=True, null=True, verbose_name='母ID')),
                ('f_ele_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='父电子耳号')),
                ('f_pre_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='父防疫耳号')),
                ('m_ele_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='母电子耳号')),
                ('m_pre_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='母防疫耳号')),
                ('f_staff', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员')),
                ('f_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('img_positive', models.ImageField(blank=True, null=True, upload_to='images/pos/%Y/%m/%d', verbose_name='正面照片')),
                ('img_left', models.ImageField(blank=True, null=True, upload_to='images/left/%Y/%m/%d', verbose_name='左侧照片')),
                ('img_right', models.ImageField(blank=True, null=True, upload_to='images/right/%Y/%m/%d', verbose_name='右侧照片')),
                ('note', models.TextField(blank=True, max_length=300, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '羔羊信息',
                'verbose_name_plural': '羔羊信息',
            },
        ),
        migrations.AlterField(
            model_name='pregnantinfo',
            name='breeding_id',
            field=models.IntegerField(verbose_name='配种信息id'),
        ),
    ]
