# Generated by Django 3.0.7 on 2021-01-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_breed', '0002_auto_20210105_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='export_breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_id', models.IntegerField(blank=True, null=True, verbose_name='配种信息id')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name': '导出配种所以信息',
                'verbose_name_plural': '导出配种所有信息',
            },
        ),
    ]
