# Generated by Django 3.0.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_breed', '0005_auto_20210411_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='artificialfeedinginfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='weaninginfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='breedinginfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='postnatalinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='pregnantinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='semencollectinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
    ]
