# Generated by Django 3.0.7 on 2021-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, verbose_name='身份证号码'),
        ),
    ]
