# Generated by Django 3.0.7 on 2020-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugbathinfo',
            name='drug_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='药品信息'),
        ),
        migrations.AlterField(
            model_name='drugbathinfo',
            name='out_time',
            field=models.DateField(verbose_name='出库时间'),
        ),
    ]
