# Generated by Django 3.0.7 on 2020-10-21 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('d_health', '0002_auto_20201021_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='cur_time',
            field=models.DateField(blank=True, null=True, verbose_name='治愈时间'),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='disease_time',
            field=models.DateField(blank=True, null=True, verbose_name='发病时间'),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='out_time',
            field=models.DateField(blank=True, null=True, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='treatment_time',
            field=models.DateField(blank=True, null=True, verbose_name='诊疗时间'),
        ),
        migrations.AlterField(
            model_name='drugbathinfo',
            name='f_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='drugbathinfo',
            name='out_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='drugbathinfo',
            name='take_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='用药时间'),
        ),
        migrations.AlterField(
            model_name='immunizationinfo',
            name='imm_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='接种日期'),
        ),
        migrations.AlterField(
            model_name='immunizationinfo',
            name='out_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出库时间'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='Ab_color',
            field=models.IntegerField(blank=True, choices=[(0, '黄'), (1, '百'), (2, '红'), (3, '绿')], null=True, verbose_name='产后胎衣颜色'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='Ab_smell',
            field=models.IntegerField(blank=True, choices=[(0, '正常'), (1, '血腥'), (2, '血臭')], null=True, verbose_name='产后胎衣颜色'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='f_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='nur_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='护理时间'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='prenatal_paralysi',
            field=models.BooleanField(blank=True, choices=[(True, '是'), (False, '否')], null=True, verbose_name='产前瘫痪'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='swelling',
            field=models.BooleanField(blank=True, choices=[(True, '是'), (False, '否')], null=True, verbose_name='乳房肿胀'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='testis_shape',
            field=models.BooleanField(blank=True, choices=[(True, '正常'), (False, '不正常')], null=True, verbose_name='睾丸形状'),
        ),
        migrations.AlterField(
            model_name='nursinginfo',
            name='uterus_fall',
            field=models.BooleanField(blank=True, choices=[(True, '是'), (False, '否')], null=True, verbose_name='子宫脱落'),
        ),
        migrations.AlterField(
            model_name='quarantineinfo',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='采样日期'),
        ),
        migrations.AlterField(
            model_name='quarantineinfo',
            name='result1',
            field=models.IntegerField(blank=True, choices=[(0, '瘦肉精(合格)'), (1, '瘦肉精(不合格)')], null=True, verbose_name='监测结果1'),
        ),
        migrations.AlterField(
            model_name='quarantineinfo',
            name='result2',
            field=models.IntegerField(blank=True, choices=[(0, '布病(阴性)'), (1, '布病(阳性)')], null=True, verbose_name='监测结果2'),
        ),
        migrations.AlterField(
            model_name='quarantineinfo',
            name='result3',
            field=models.IntegerField(blank=True, choices=[(0, '测孕(阴性)'), (1, '测孕(阳性)')], null=True, verbose_name='监测结果3'),
        ),
        migrations.AlterField(
            model_name='quarantineinfo',
            name='situation',
            field=models.IntegerField(blank=True, choices=[(0, '允许销售'), (1, '不允许销售'), (2, '治疗'), (3, '淘汰')], null=True, verbose_name='处理情况'),
        ),
    ]
