# Generated by Django 3.0.7 on 2020-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_health', '0004_auto_20201021_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='cur_effect',
            field=models.IntegerField(blank=True, choices=[(0, '治愈'), (1, '淘汰'), (2, '死亡')], null=True, verbose_name='治愈效果'),
        ),
    ]
