# Generated by Django 3.0.7 on 2020-10-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_health', '0005_auto_20201021_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nursinginfo',
            options={'verbose_name': '护理信息', 'verbose_name_plural': '护理信息'},
        ),
    ]
