# Generated by Django 3.0.7 on 2020-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_health', '0006_auto_20201026_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='drug_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='是否国家允许的药物'),
        ),
    ]
