# Generated by Django 3.0.7 on 2020-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '疫苗'), (1, '药品')], verbose_name='类别')),
                ('cname', models.CharField(max_length=20, verbose_name='名称')),
                ('explain', models.TextField(blank=True, max_length=50, null=True, verbose_name='说明')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name': '疫苗药品信息',
                'verbose_name_plural': '疫苗药品信息',
            },
        ),
    ]
