# Generated by Django 3.0.7 on 2021-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20210411_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_suppliersinfo',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='f_suppliersinfo',
            name='operation',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='v_suppliersinfo',
            name='operation',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='操作'),
        ),
    ]
