# Generated by Django 3.0.7 on 2020-09-26 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disinfectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(verbose_name='圈舍号')),
                ('date', models.DateField(blank=True, verbose_name='消毒日期')),
                ('staff', models.CharField(blank=True, max_length=8, verbose_name='消毒人员')),
                ('drug', models.CharField(blank=True, max_length=50, verbose_name='消毒药物')),
                ('dose', models.FloatField(blank=True, null=True, verbose_name='稀释比例(重量/平米)')),
                ('method', models.IntegerField(blank=True, choices=[(0, '喷雾消毒'), (1, '固状消毒')], verbose_name='消毒方法')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name_plural': '圈舍消毒信息',
            },
        ),
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, default=0, verbose_name='上级id')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='名称')),
                ('build_time', models.DateField(verbose_name='建设时间')),
                ('function', models.IntegerField(choices=[(0, '繁殖母羊舍'), (1, '母羊产房'), (2, '母羔哺乳舍'), (3, '育成舍(2月-8月的种羊)'), (4, '种公羊舍'), (5, '育肥羊舍(2月-7个月)'), (6, '隔离羊舍')], verbose_name='功能')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='面积')),
                ('h_type', models.IntegerField(choices=[(0, '单排'), (1, '双排')], verbose_name='羊舍类型')),
                ('h_lwh', models.CharField(blank=True, max_length=40, verbose_name='圈舍长宽高')),
                ('sports_lwh', models.CharField(blank=True, max_length=40, verbose_name='运动场长宽高')),
                ('sheep_type', models.IntegerField(blank=True, null=True, verbose_name='养羊类型')),
                ('sheep_quantity', models.IntegerField(blank=True, null=True, verbose_name='羊只数量')),
                ('area_pro', models.CharField(blank=True, max_length=100, verbose_name='羊只面积比例')),
                ('staff', models.CharField(blank=True, max_length=8, verbose_name='管理人员')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name_plural': '圈舍基本信息',
            },
        ),
        migrations.CreateModel(
            name='maintenanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(verbose_name='圈舍号')),
                ('M_condition', models.TextField(blank=True, max_length=200, verbose_name='维护情况')),
                ('M_details', models.TextField(blank=True, max_length=200, verbose_name='维修内容')),
                ('M_time', models.DateField(blank=True, verbose_name='维护时间')),
                ('M_cost', models.FloatField(blank=True, verbose_name='维护成本')),
                ('f_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('f_staff', models.IntegerField(blank=True, null=True, verbose_name='创建人员')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name_plural': '圈舍维护',
            },
        ),
        migrations.CreateModel(
            name='transferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_id', models.IntegerField(verbose_name='羊基本信息id')),
                ('new_house_id', models.IntegerField(null=True, verbose_name='新圈舍号')),
                ('old_house_id', models.IntegerField(null=True, verbose_name='旧圈舍号')),
                ('reason', models.IntegerField(blank=True, null=True, verbose_name='转移原因')),
                ('trans_time', models.DateField(blank=True, verbose_name='转移时间')),
                ('sheep_type', models.CharField(blank=True, max_length=20, verbose_name='羊只类型')),
                ('f_date', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('f_staff', models.IntegerField(blank=True, null=True, verbose_name='创建人员')),
                ('belong', models.IntegerField(verbose_name='羊场域')),
            ],
            options={
                'verbose_name_plural': '圈舍转移',
            },
        ),
    ]
