# Generated by Django 3.0.7 on 2020-10-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0002_disinfectioninfoadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disinfectionInfoAdmin',
        ),
    ]
