# Generated by Django 3.0.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0003_delete_disinfectioninfoadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='maintenanceinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='transferinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
    ]
