# Generated by Django 3.0.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding_out',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='feedingin',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='vaccine_in',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='vaccine_out',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
    ]
