# Generated by Django 3.0.7 on 2020-10-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_slaughter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicinfo',
            name='basic_id',
            field=models.CharField(max_length=16, verbose_name='羊只基本信息ID'),
        ),
        migrations.AlterField(
            model_name='economicinfo',
            name='belong',
            field=models.CharField(default='zhiHao', max_length=40, verbose_name='羊场域'),
        ),
        migrations.AlterField(
            model_name='g_salesinfo',
            name='sales_order',
            field=models.CharField(max_length=10, verbose_name='销售单号'),
        ),
        migrations.AlterField(
            model_name='g_salesinfo',
            name='type',
            field=models.IntegerField(choices=[(0, '羊粪'), (1, '羊毛'), (2, '羊皮')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='s_salesinfo',
            name='sales_order',
            field=models.CharField(max_length=10, verbose_name='销售单号'),
        ),
        migrations.AlterField(
            model_name='slaughtersegmentinfo',
            name='basic_id',
            field=models.CharField(max_length=16, verbose_name='羊只基本信息ID'),
        ),
    ]
