# Generated by Django 3.0.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_slaughter', '0002_auto_20201028_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='binformationinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='economicinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='g_salesinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AddField(
            model_name='s_salesinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='slaughtersegmentinfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
    ]
