# Generated by Django 3.0.7 on 2021-06-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_slaughter', '0003_auto_20210411_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binformationinfo',
            name='variety',
            field=models.IntegerField(choices=[(0, '湖羊'), (1, '小尾寒羊'), (2, '无角道赛特'), (3, '道寒杂交F1'), (4, '白杜泊'), (5, '白萨福克'), (6, '杜湖杂交'), (7, '萨湖杂交'), (8, '杜寒杂交'), (9, '萨寒杂交'), (10, '道湖')], verbose_name='品种'),
        ),
    ]
