# Generated by Django 3.0.7 on 2021-03-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0004_auto_20210307_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedhouseinfo',
            name='billing_unit',
            field=models.CharField(blank=True, default='kg', max_length=3, null=True, verbose_name='重量单位'),
        ),
        migrations.AddField(
            model_name='feedhouseinfo',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='重量'),
        ),
    ]
