# Generated by Django 3.0.7 on 2020-10-08 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20201004_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='f_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='manu_info_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产地名'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='purpose',
            field=models.IntegerField(blank=True, choices=[(0, '育苗'), (1, '育肥')], null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '母'), (1, '公')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, '死亡'), (1, '正常'), (2, '销售')], null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='variety',
            field=models.IntegerField(blank=True, choices=[(0, '湖羊'), (1, '小尾'), (2, '黑山'), (3, '小尾3'), (4, '小尾4'), (5, '小尾5'), (6, '小尾6')], null=True, verbose_name='品种'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, '白'), (1, '黑'), (2, '咖'), (3, '混合色')], default=0, verbose_name='毛色'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '细毛'), (1, '粗毛'), (2, '绒毛'), (3, '细毛-同质'), (4, '粗毛同质')], verbose_name='羊毛类型'),
        ),
    ]
