# Generated by Django 3.0.7 on 2021-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20201028_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='breederconditioninfo',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, '白'), (1, '黑'), (2, '咖'), (3, '混合色')], default=0, verbose_name='毛色'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breederconditioninfo',
            name='mon_age',
            field=models.IntegerField(blank=True, choices=[(0, '2月龄'), (1, '6月龄'), (2, '12月龄'), (3, '24月龄')], default=0, verbose_name='月龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breederconditioninfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '一级'), (1, '二级'), (2, '三级')], default=0, verbose_name='外貌等级'),
            preserve_default=False,
        ),
    ]
