# Generated by Django 3.0.7 on 2021-01-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20210108_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, '白'), (1, '黑'), (2, '咖'), (3, '混合色')], null=True, verbose_name='毛色'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '一级'), (1, '二级'), (2, '三级')], null=True, verbose_name='外貌等级'),
        ),
    ]
