# Generated by Django 3.0.7 on 2021-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20210112_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '特级'), (1, '一级'), (2, '二级'), (3, '三级'), (9, '未评级')], null=True, verbose_name='外貌等级'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '特级'), (1, '一级'), (2, '二级'), (3, '三级'), (9, '未评级')], verbose_name='外貌等级'),
        ),
        migrations.AlterField(
            model_name='milkperformance',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
        migrations.AlterField(
            model_name='skinperformance',
            name='f_staff',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人员'),
        ),
    ]
