# Generated by Django 3.0.7 on 2021-06-19 16:02

import apps.valid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20210411_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'ordering': ('-f_date',), 'verbose_name': '羊只基本信息', 'verbose_name_plural': '羊只基本信息'},
        ),
        migrations.AlterModelOptions(
            name='breederconditioninfo',
            options={'verbose_name': '种羊体况', 'verbose_name_plural': '种羊体况'},
        ),
        migrations.AlterModelOptions(
            name='cutinfo',
            options={'verbose_name': '剪毛信息', 'verbose_name_plural': '剪毛信息'},
        ),
        migrations.AlterModelOptions(
            name='productivityinfo',
            options={'verbose_name': '生产性能详细', 'verbose_name_plural': '生产性能详细'},
        ),
        migrations.AlterModelOptions(
            name='sportsinfo',
            options={'verbose_name': '运动数据', 'verbose_name_plural': '运动数据'},
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='purpose',
            field=models.IntegerField(blank=True, choices=[(0, '种羊(待分类)'), (1, '育肥'), (2, '哺乳羔羊'), (5, '繁殖公羊'), (6, '繁殖母羊'), (8, '育成羊')], null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, '母'), (0, '公')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='variety',
            field=models.IntegerField(blank=True, choices=[(0, '湖羊'), (1, '小尾寒羊'), (2, '无角道赛特'), (3, '道寒杂交F1'), (4, '白杜泊'), (5, '白萨福克'), (6, '杜湖杂交'), (7, '萨湖杂交'), (8, '杜寒杂交'), (9, '萨寒杂交'), (10, '道湖')], null=True, verbose_name='品种'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='color',
            field=models.IntegerField(blank=True, choices=[(0, '白'), (1, '黑'), (2, '咖'), (3, '混合色')], null=True, validators=[apps.valid.valid_null], verbose_name='毛色'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='mon_age',
            field=models.IntegerField(blank=True, choices=[(0, '2月龄'), (1, '6月龄'), (2, '12月龄'), (3, '24月龄')], null=True, verbose_name='月龄'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='rank',
            field=models.IntegerField(blank=True, choices=[(0, '特级'), (1, '一级'), (2, '二级'), (3, '三级'), (9, '未评级')], null=True, verbose_name='外貌等级'),
        ),
        migrations.AlterField(
            model_name='breederconditioninfo',
            name='testis_shape',
            field=models.BooleanField(blank=True, choices=[(True, '正常'), (False, '非正常')], null=True, verbose_name='睾丸形状'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='color',
            field=models.IntegerField(choices=[(0, '白'), (1, '黑'), (2, '咖'), (3, '混合色')], default=0, null=True, verbose_name='毛色'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='cut_time',
            field=models.IntegerField(choices=[(3, '3月'), (6, '6月'), (9, '9月')], null=True, verbose_name='剪毛时间'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='rank',
            field=models.IntegerField(choices=[(0, '细毛'), (1, '粗毛'), (2, '绒毛'), (3, '细毛-同质'), (4, '粗毛同质')], null=True, verbose_name='羊毛类型'),
        ),
        migrations.AlterField(
            model_name='cutinfo',
            name='variety',
            field=models.IntegerField(choices=[(0, '湖羊'), (1, '小尾寒羊'), (2, '无角道赛特'), (3, '道寒杂交F1'), (4, '白杜泊'), (5, '白萨福克'), (6, '杜湖杂交'), (7, '萨湖杂交'), (8, '杜寒杂交'), (9, '萨寒杂交'), (10, '道湖')], null=True, verbose_name='品种'),
        ),
    ]
